version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALLOWED_ORIGINS=http://localhost:3001,https://syncdoc-frontend.onrender.com
      - COOKIE_SECRET=change_this_to_a_secure_secret_in_production
      - COOKIE_MAX_AGE=2592000000
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - backend
    restart: always
