services:
  # Backend Service
  - type: web
    name: syncdoc-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && bun install && bun run build
    startCommand: cd backend && bun start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://syncdoc-frontend.onrender.com,http://localhost:3000
      - key: COOKIE_SECRET
        generateValue: true
      - key: COOKIE_MAX_AGE
        value: 2592000000

  # Frontend Service
  - type: web
    name: syncdoc-frontend
    env: node
    region: oregon
    buildCommand: cd frontend && bun install
    startCommand: cd frontend && bun start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_BASE_URL
        value: https://syncdoc-backend.onrender.com/api
      - key: SOCKET_URL
        value: https://syncdoc-backend.onrender.com
